name: fitness_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  #Firebase
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  provider: ^4.3.2+1

  font_awesome_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
